export type BlockStyleCapabilities = {
  display: boolean;
  textAlign: boolean;
  flex: boolean;
  grid: boolean;
  container: boolean;
  maxWidth: boolean;
  padding: boolean;
  margin: boolean;
  typography: boolean;
  textColor: boolean;
  border: boolean;
  radius: boolean;
  shadow: boolean;
  background: boolean;
  stylePreview: boolean;
};

const ALL_DISABLED: BlockStyleCapabilities = {
  display: false,
  textAlign: false,
  flex: false,
  grid: false,
  container: false,
  maxWidth: false,
  padding: false,
  margin: false,
  typography: false,
  textColor: false,
  border: false,
  radius: false,
  shadow: false,
  background: false,
  stylePreview: false,
};

const DEFAULT_CONTENT_BLOCK: BlockStyleCapabilities = {
  display: false,
  textAlign: true,
  flex: false,
  grid: false,
  container: true,
  maxWidth: true,
  padding: true,
  margin: true,
  typography: true,
  textColor: true,
  border: true,
  radius: true,
  shadow: true,
  background: true,
  stylePreview: true,
};

const DEFAULT_WRAPPER_BLOCK: BlockStyleCapabilities = {
  display: false,
  textAlign: true,
  flex: false,
  grid: false,
  container: true,
  maxWidth: true,
  padding: true,
  margin: true,
  typography: false,
  textColor: true,
  border: true,
  radius: true,
  shadow: true,
  background: true,
  stylePreview: true,
};

const DEFAULT_COMPACT_BLOCK: BlockStyleCapabilities = {
  display: false,
  textAlign: false,
  flex: false,
  grid: false,
  container: false,
  maxWidth: false,
  padding: true,
  margin: true,
  typography: false,
  textColor: true,
  border: true,
  radius: true,
  shadow: true,
  background: true,
  stylePreview: true,
};

const FAMILY_DEFAULTS: Array<{
  test: (type: string) => boolean;
  capabilities: BlockStyleCapabilities;
}> = [
  {
    test: (type) => type.startsWith("Atomic/"),
    capabilities: DEFAULT_CONTENT_BLOCK,
  },
  {
    test: (type) => type === "Hero" || type.startsWith("Hero/"),
    capabilities: {
      ...DEFAULT_CONTENT_BLOCK,
      display: true,
      flex: true,
      textAlign: true,
    },
  },
  {
    test: (type) => type.startsWith("Header/"),
    capabilities: {
      ...DEFAULT_WRAPPER_BLOCK,
      display: false,
      textAlign: false,
      typography: false,
    },
  },
  {
    test: (type) => type.startsWith("Footer/"),
    capabilities: {
      ...DEFAULT_WRAPPER_BLOCK,
      textAlign: false,
      typography: false,
    },
  },
  {
    test: (type) => type.startsWith("Product"),
    capabilities: {
      ...DEFAULT_WRAPPER_BLOCK,
      grid: false,
      flex: false,
      display: false,
    },
  },
  {
    test: (type) =>
      [
        "CategoryGrid/V1",
        "BrandGrid/V1",
        "BestSellers/V1",
        "StoreLocator/V1",
        "BundleOffer/V1",
        "PricingTable/V1",
        "BentoGrid/V1",
        "ComparisonTable/V1",
        "MediaGalleryMasonry/V1",
        "InteractiveTabs/V1",
        "StatsCounter/V1",
        "LogosCloud/V1",
        "FAQAccordion/V1",
      ].includes(type),
    capabilities: {
      ...DEFAULT_WRAPPER_BLOCK,
      grid: false,
      flex: false,
      display: false,
    },
  },
  {
    test: (type) =>
      [
        "BannerCTA/V1",
        "FeaturesGrid/V1",
        "Testimonials/V1",
        "BeforeAfterSlider/V1",
        "StickyPromoBar/V1",
        "TestimonialCarousel/V1",
        "SpotlightCards/V1",
        "ProcessTimeline/V1",
        "VideoHeroLite/V1",
        "KPIRibbon/V1",
        "ContentSplitShowcase/V1",
        "SocialProofTicker/V1",
        "NewsletterSignup/V1",
      ].includes(type),
    capabilities: DEFAULT_CONTENT_BLOCK,
  },
  {
    test: (type) =>
      ["MegaMenu/V1", "CartPage/V1", "Form/V1"].includes(type),
    capabilities: {
      ...DEFAULT_CONTENT_BLOCK,
      display: false,
      flex: false,
      grid: false,
    },
  },
  {
    test: (type) => ["CartSummary/V1", "AddToCart/V1", "FloatingCTA/V1"].includes(type),
    capabilities: {
      ...DEFAULT_COMPACT_BLOCK,
      padding: false,
      background: false,
      border: false,
      radius: false,
      shadow: false,
      stylePreview: false,
    },
  },
  {
    test: (type) => type === "Utility/Spacer",
    capabilities: {
      ...ALL_DISABLED,
      margin: true,
    },
  },
  {
    test: (type) => type === "Utility/Divider",
    capabilities: {
      ...ALL_DISABLED,
      margin: true,
    },
  },
  {
    test: (type) => type === "Utility/RichText",
    capabilities: {
      ...DEFAULT_CONTENT_BLOCK,
      display: false,
      flex: false,
      grid: false,
    },
  },
  {
    test: (type) => type === "Layout/Section",
    capabilities: ALL_DISABLED,
  },
];

const BLOCK_OVERRIDES: Record<string, Partial<BlockStyleCapabilities>> = {
  "ProductGrid/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
  },
  "ProductList/V1": {
    textAlign: false,
    typography: false,
    display: false,
    flex: false,
    grid: false,
  },
  "ProductDetail/V1": {
    grid: false,
    typography: false,
    display: false,
    flex: false,
    textAlign: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "Header/V1": {
    background: true,
    border: true,
    radius: true,
    shadow: true,
  },
  "Footer/V1": {
    background: true,
    border: true,
    radius: true,
    shadow: true,
  },
  "MegaMenu/V1": {
    textAlign: false,
    typography: false,
  },
  "StickyPromoBar/V1": {
    container: false,
    maxWidth: false,
    padding: false,
    margin: false,
    border: false,
    radius: false,
  },
  "SocialProofTicker/V1": {
    typography: false,
    textAlign: false,
    display: false,
    flex: false,
    grid: false,
  },
  "StatsCounter/V1": {
    typography: false,
    display: false,
    flex: false,
    grid: false,
  },
  "LogosCloud/V1": {
    typography: false,
    textAlign: false,
    display: false,
    flex: false,
    grid: false,
  },
  "Utility/Spacer": {
    padding: false,
    stylePreview: false,
  },
  "Utility/Divider": {
    border: false,
    textColor: false,
    background: false,
    radius: false,
    shadow: false,
    stylePreview: false,
  },
  "FloatingCTA/V1": {
    margin: false,
    textColor: false,
    background: false,
    border: false,
    radius: false,
    shadow: false,
    stylePreview: false,
  },
  "AddToCart/V1": {
    textAlign: false,
    typography: false,
    textColor: false,
  },
  "CartSummary/V1": {
    textAlign: false,
    typography: false,
    textColor: false,
    background: false,
    border: false,
    radius: false,
    shadow: false,
    stylePreview: false,
  },
  "CategoryGrid/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "BrandGrid/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "BestSellers/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "StoreLocator/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "BundleOffer/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "PricingTable/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "ProductHighlight/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "MegaMenu/V1": {
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "Form/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "CartPage/V1": {
    textAlign: false,
    typography: false,
    textColor: false,
    background: false,
    border: false,
    radius: false,
    shadow: false,
    stylePreview: false,
  },
  "BannerCTA/V1": {
    container: false,
    maxWidth: false,
    typography: false,
    textColor: false,
  },
  "FeaturesGrid/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "Testimonials/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "BeforeAfterSlider/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "TestimonialCarousel/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "SpotlightCards/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "ProcessTimeline/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "VideoHeroLite/V1": {
    typography: false,
    textColor: false,
    container: false,
    maxWidth: false,
  },
  "ContentSplitShowcase/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "NewsletterSignup/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "InteractiveTabs/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "KPIRibbon/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "MediaGalleryMasonry/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "BentoGrid/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "ComparisonTable/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "FAQAccordion/V1": {
    textAlign: false,
    typography: false,
    container: false,
    maxWidth: false,
    textColor: false,
  },
  "Atomic/Text": {
    display: false,
    flex: false,
    grid: false,
    container: false,
    maxWidth: false,
    padding: false,
    margin: true,
    typography: true,
    textColor: true,
    border: false,
    radius: false,
    shadow: false,
    background: false,
  },
  "Atomic/Image": {
    display: false,
    textAlign: false,
    flex: false,
    grid: false,
    container: false,
    maxWidth: false,
    padding: false,
    margin: true,
    typography: false,
    textColor: false,
    border: false,
    radius: false,
    shadow: false,
    background: false,
    stylePreview: false,
  },
  "Atomic/Video": {
    display: false,
    textAlign: false,
    flex: false,
    grid: false,
    container: false,
    maxWidth: false,
    padding: false,
    margin: true,
    typography: false,
    textColor: false,
    border: false,
    radius: false,
    shadow: false,
    background: false,
    stylePreview: false,
  },
  "Atomic/Button": {
    display: false,
    textAlign: false,
    flex: false,
    grid: false,
    container: false,
    maxWidth: false,
    padding: false,
    margin: true,
    typography: false,
    textColor: false,
    border: false,
    radius: false,
    shadow: false,
    background: false,
    stylePreview: false,
  },
  "Atomic/Icon": {
    display: false,
    textAlign: false,
    flex: false,
    grid: false,
    container: false,
    maxWidth: false,
    padding: false,
    margin: true,
    typography: false,
    textColor: true,
    border: false,
    radius: false,
    shadow: false,
    background: false,
  },
  "Atomic/Divider": {
    display: false,
    textAlign: false,
    flex: false,
    grid: false,
    container: false,
    maxWidth: false,
    padding: false,
    margin: true,
    typography: false,
    textColor: false,
    border: false,
    radius: false,
    shadow: false,
    background: false,
    stylePreview: false,
  },
  "Atomic/Spacer": {
    display: false,
    textAlign: false,
    flex: false,
    grid: false,
    container: false,
    maxWidth: false,
    padding: false,
    margin: true,
    typography: false,
    textColor: false,
    border: false,
    radius: false,
    shadow: false,
    background: false,
    stylePreview: false,
  },
  "Atomic/Badge": {
    display: false,
    textAlign: false,
    flex: false,
    grid: false,
    container: false,
    maxWidth: false,
    padding: false,
    margin: true,
    typography: false,
    textColor: false,
    border: false,
    radius: false,
    shadow: false,
    background: false,
  },
  "Atomic/List": {
    display: false,
    textAlign: false,
    flex: false,
    grid: false,
    container: false,
    maxWidth: false,
    padding: false,
    margin: true,
    typography: false,
    textColor: false,
    border: false,
    radius: false,
    shadow: false,
    background: false,
  },
  "Atomic/Card": {
    display: false,
    textAlign: false,
    flex: false,
    grid: false,
    container: false,
    maxWidth: false,
    padding: false,
    margin: true,
    typography: false,
    textColor: false,
    border: false,
    radius: false,
    shadow: false,
    background: false,
  },
  "Atomic/Accordion": {
    display: false,
    textAlign: false,
    flex: false,
    grid: false,
    container: false,
    maxWidth: false,
    padding: false,
    margin: true,
    typography: false,
    textColor: false,
    border: false,
    radius: false,
    shadow: false,
    background: false,
  },
  "Atomic/Menu": {
    display: false,
    textAlign: false,
    flex: false,
    grid: false,
    container: false,
    maxWidth: false,
    padding: false,
    margin: true,
    typography: false,
    textColor: false,
    border: false,
    radius: false,
    shadow: false,
    background: false,
  },
  "Atomic/Countdown": {
    display: false,
    textAlign: false,
    flex: false,
    grid: false,
    container: false,
    maxWidth: false,
    padding: false,
    margin: true,
    typography: false,
    textColor: true,
    border: false,
    radius: false,
    shadow: false,
    background: false,
  },
  "Atomic/Embed": {
    display: false,
    textAlign: false,
    flex: false,
    grid: false,
    container: false,
    maxWidth: false,
    padding: false,
    margin: true,
    typography: false,
    textColor: false,
    border: false,
    radius: false,
    shadow: false,
    background: false,
    stylePreview: false,
  },
  "Atomic/Group": {
    display: false,
    textAlign: false,
    flex: false,
    grid: false,
    container: false,
    maxWidth: false,
    padding: false,
    margin: true,
    typography: false,
    textColor: false,
    border: false,
    radius: false,
    shadow: false,
    background: false,
    stylePreview: false,
  },
};

export function getBlockStyleCapabilities(
  type: string,
): BlockStyleCapabilities {
  const familyMatch =
    FAMILY_DEFAULTS.find((entry) => entry.test(type))?.capabilities ??
    DEFAULT_CONTENT_BLOCK;
  return {
    ...familyMatch,
    ...(BLOCK_OVERRIDES[type] || {}),
  };
}

export function hasAnyStyleCapability(capabilities: BlockStyleCapabilities) {
  return Object.values(capabilities).some(Boolean);
}
