export const INDUSTRY_TEMPLATES = {
  fashion: [
    {
      code: "size",
      name: "Size",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: [
        "XS",
        "S",
        "M",
        "L",
        "XL",
        "XXL",
        "3XL",
        "4XL",
        "One Size",
        "Custom",
      ],
    },
    {
      code: "color",
      name: "Color",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: [
        "Black",
        "White",
        "Grey",
        "Navy",
        "Red",
        "Pink",
        "Green",
        "Blue",
        "Beige",
        "Brown",
        "Yellow",
        "Purple",
        "Maroon",
        "Olive",
        "Teal",
        "Orange",
        "Multi",
      ],
    },
    {
      code: "material",
      name: "Material",
      type: "select",
      is_filterable: true,
      options: [
        "Cotton",
        "Polyester",
        "Nylon",
        "Wool",
        "Linen",
        "Silk",
        "Denim",
        "Leather",
        "Suede",
        "Velvet",
        "Chiffon",
        "Lace",
        "Rayon",
        "Viscose",
        "Spandex",
        "Modal",
      ],
    },
    {
      code: "fit",
      name: "Fit",
      type: "select",
      is_filterable: true,
      options: [
        "Slim",
        "Regular",
        "Relaxed",
        "Oversized",
        "Skinny",
        "Straight",
        "Bootcut",
        "Flared",
        "Athletic",
      ],
    },
    {
      code: "pattern",
      name: "Pattern",
      type: "select",
      is_filterable: true,
      options: [
        "Solid",
        "Striped",
        "Checkered",
        "Floral",
        "Geometric",
        "Polka Dot",
        "Camouflage",
        "Animal Print",
        "Paisley",
        "Tie Dye",
        "Abstract",
      ],
    },
    {
      code: "sleeve",
      name: "Sleeve",
      type: "select",
      is_filterable: true,
      options: [
        "Sleeveless",
        "Short Sleeve",
        "3/4 Sleeve",
        "Long Sleeve",
        "Cap Sleeve",
        "Bell Sleeve",
      ],
    },
    {
      code: "neck",
      name: "Neckline",
      type: "select",
      is_filterable: true,
      options: [
        "Round Neck",
        "V-Neck",
        "Crew Neck",
        "Polo",
        "Hooded",
        "Turtleneck",
        "Off Shoulder",
        "Square Neck",
        "Boat Neck",
        "Halters",
      ],
    },
    {
      code: "length",
      name: "Length",
      type: "select",
      is_filterable: true,
      options: [
        "Crop",
        "Regular",
        "Longline",
        "Mini",
        "Midi",
        "Maxi",
        "Ankle",
        "Floor",
      ],
    },
    {
      code: "style",
      name: "Style",
      type: "select",
      is_filterable: true,
      options: [
        "Casual",
        "Formal",
        "Athleisure",
        "Streetwear",
        "Bohemian",
        "Vintage",
        "Minimalist",
        "Preppy",
        "Grunge",
      ],
    },
    {
      code: "occasion",
      name: "Occasion",
      type: "select",
      is_filterable: true,
      options: [
        "Daily Wear",
        "Party",
        "Office",
        "Wedding",
        "Sports",
        "Festive",
        "Vacation",
      ],
    },
    {
      code: "gender",
      name: "Gender",
      type: "select",
      is_filterable: true,
      options: ["Men", "Women", "Unisex", "Kids"],
    },
    {
      code: "sustainable",
      name: "Sustainable",
      type: "boolean",
      is_filterable: true,
    },
  ],

  shoes: [
    {
      code: "size",
      name: "Size",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: [
        "UK 3",
        "UK 4",
        "UK 5",
        "UK 6",
        "UK 7",
        "UK 8",
        "UK 9",
        "UK 10",
        "UK 11",
        "UK 12",
        "EU 36",
        "EU 37",
        "EU 38",
        "EU 39",
        "EU 40",
        "EU 41",
        "EU 42",
        "EU 43",
        "EU 44",
        "EU 45",
      ],
    },
    {
      code: "color",
      name: "Color",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: [
        "Black",
        "White",
        "Grey",
        "Brown",
        "Tan",
        "Navy",
        "Red",
        "Beige",
        "Olive",
        "Blue",
        "Multi",
      ],
    },
    {
      code: "width",
      name: "Width",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: ["Narrow", "Medium", "Wide", "Extra Wide"],
    },
    {
      code: "material",
      name: "Upper Material",
      type: "select",
      is_filterable: true,
      options: [
        "Leather",
        "Suede",
        "Canvas",
        "Mesh",
        "Synthetic",
        "Nubuck",
        "Knit",
        "Rubber",
      ],
    },
    {
      code: "closure",
      name: "Closure",
      type: "select",
      is_filterable: true,
      options: ["Lace-up", "Slip-on", "Velcro", "Buckle", "Zip", "Pull-on"],
    },
    {
      code: "heel_height",
      name: "Heel Height",
      type: "select",
      is_filterable: true,
      options: [
        "Flat",
        "Low (1-2 cm)",
        "Mid (3-6 cm)",
        "High (7+ cm)",
        "Wedge",
      ],
    },
    {
      code: "toe_style",
      name: "Toe Style",
      type: "select",
      is_filterable: true,
      options: ["Round", "Pointed", "Square", "Almond", "Peep Toe"],
    },
    {
      code: "type",
      name: "Shoe Type",
      type: "select",
      is_filterable: true,
      options: [
        "Sneakers",
        "Boots",
        "Sandals",
        "Loafers",
        "Formal",
        "Sports",
        "Slippers",
      ],
    },
  ],

  jewelry: [
    {
      code: "metal",
      name: "Metal",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: [
        "Gold",
        "Rose Gold",
        "White Gold",
        "Yellow Gold",
        "Silver",
        "Platinum",
        "Stainless Steel",
        "Titanium",
        "Brass",
      ],
    },
    {
      code: "color",
      name: "Gemstone/Color",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: [
        "Black",
        "White",
        "Red",
        "Blue",
        "Green",
        "Pink",
        "Yellow",
        "Purple",
        "Clear",
        "Multi",
      ],
    },
    {
      code: "size",
      name: "Size",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: [
        "Adjustable",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "S",
        "M",
        "L",
        "One Size",
      ],
    },
    {
      code: "stone",
      name: "Gemstone",
      type: "select",
      is_filterable: true,
      options: [
        "Diamond",
        "Ruby",
        "Sapphire",
        "Emerald",
        "Zircon",
        "Pearl",
        "None",
        "Amethyst",
        "Topaz",
        "Opal",
        "Turquoise",
      ],
    },
    {
      code: "purity",
      name: "Purity",
      type: "select",
      is_filterable: true,
      options: ["14K", "18K", "22K", "24K", "925 Sterling", "950 Platinum"],
    },
    {
      code: "plating",
      name: "Plating",
      type: "select",
      is_filterable: true,
      options: [
        "Gold Plated",
        "Rose Gold Plated",
        "Rhodium",
        "None",
        "Silver Plated",
      ],
    },
    {
      code: "type",
      name: "Jewelry Type",
      type: "select",
      is_filterable: true,
      options: [
        "Ring",
        "Necklace",
        "Earrings",
        "Bracelet",
        "Pendant",
        "Anklet",
      ],
    },
  ],

  sports_outdoor: [
    {
      code: "size",
      name: "Size",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
    },
    {
      code: "color",
      name: "Color",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: [
        "Black",
        "White",
        "Grey",
        "Navy",
        "Red",
        "Blue",
        "Green",
        "Yellow",
        "Neon",
      ],
    },
    {
      code: "sport_type",
      name: "Sport",
      type: "select",
      is_filterable: true,
      options: [
        "Running",
        "Yoga",
        "Gym",
        "Cycling",
        "Swimming",
        "Cricket",
        "Football",
        "Basketball",
        "Tennis",
        "Hiking",
        "Camping",
      ],
    },
    {
      code: "material",
      name: "Material",
      type: "select",
      is_filterable: true,
      options: [
        "Polyester",
        "Spandex",
        "Cotton Blend",
        "Nylon",
        "Neoprene",
        "Mesh",
        "Fleece",
      ],
    },
    {
      code: "gender",
      name: "Gender",
      type: "select",
      is_filterable: true,
      options: ["Men", "Women", "Unisex", "Kids"],
    },
    {
      code: "feature",
      name: "Key Feature",
      type: "select",
      is_filterable: true,
      options: [
        "Breathable",
        "Waterproof",
        "Reflective",
        "Quick Dry",
        "Padded",
      ],
    },
  ],

  furniture_home_decor: [
    { code: "color", name: "Color", type: "select", is_filterable: true },
    {
      code: "material",
      name: "Material",
      type: "select",
      is_filterable: true,
      options: [
        "Wood",
        "Metal",
        "Glass",
        "Fabric",
        "Leather",
        "MDF",
        "Particle Board",
        "Bamboo",
        "Rattan",
      ],
    },
    {
      code: "size",
      name: "Size",
      type: "select",
      is_filterable: true,
      options: [
        "Single",
        "Double",
        "Queen",
        "King",
        "Small",
        "Medium",
        "Large",
      ],
    },
    {
      code: "style",
      name: "Style",
      type: "select",
      is_filterable: true,
      options: [
        "Modern",
        "Industrial",
        "Scandinavian",
        "Vintage",
        "Rustic",
        "Minimalist",
        "Bohemian",
      ],
    },
    { code: "dimensions", name: "Dimensions", type: "text" },
    {
      code: "assembly_required",
      name: "Assembly Required",
      type: "boolean",
      is_filterable: true,
    },
    {
      code: "weight_capacity",
      name: "Weight Capacity",
      type: "number",
      suffix: "kg",
    },
  ],

  bags_luggage: [
    {
      code: "color",
      name: "Color",
      type: "select",
      is_variant: true,
      is_filterable: true,
    },
    {
      code: "size",
      name: "Size",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: [
        "Small",
        "Medium",
        "Large",
        "Cabin",
        "Check-in",
        "Backpack",
        "Tote",
      ],
    },
    {
      code: "material",
      name: "Material",
      type: "select",
      is_filterable: true,
      options: [
        "Leather",
        "Canvas",
        "Nylon",
        "Polyester",
        "PU",
        "Waterproof Fabric",
      ],
    },
    { code: "compartments", name: "Compartments", type: "number" },
    {
      code: "laptop_size",
      name: "Laptop Compatibility",
      type: "select",
      is_filterable: true,
      options: [
        'Up to 13"',
        'Up to 14"',
        'Up to 15"',
        'Up to 16"',
        'Up to 17"',
        "None",
      ],
    },
    {
      code: "waterproof",
      name: "Waterproof",
      type: "boolean",
      is_filterable: true,
    },
    {
      code: "type",
      name: "Bag Type",
      type: "select",
      is_filterable: true,
      options: [
        "Backpack",
        "Handbag",
        "Tote",
        "Duffel",
        "Suitcase",
        "Messenger",
      ],
    },
  ],

  electronics: [
    { code: "brand", name: "Brand", type: "text", is_filterable: true },
    { code: "model", name: "Model", type: "text" },
    {
      code: "ram",
      name: "RAM",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: ["2GB", "4GB", "6GB", "8GB", "12GB", "16GB", "32GB", "64GB"],
    },
    {
      code: "storage",
      name: "Storage",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: ["32GB", "64GB", "128GB", "256GB", "512GB", "1TB", "2TB", "4TB"],
    },
    {
      code: "storage_type",
      name: "Storage Type",
      type: "select",
      is_filterable: true,
      options: ["HDD", "SSD", "M.2 SSD", "NVMe", "eMMC"],
    },
    {
      code: "screen_size",
      name: "Screen Size",
      type: "select",
      is_filterable: true,
      options: ['11"', '13.3"', '14"', '15.6"', '16"', '17.3"'],
    },
    {
      code: "resolution",
      name: "Resolution",
      type: "select",
      is_filterable: true,
      options: ["HD", "Full HD", "2K", "QHD", "4K", "Retina", "8K"],
    },
    {
      code: "processor",
      name: "Processor",
      type: "select",
      is_filterable: true,
      options: [
        "Intel Core i3",
        "Intel Core i5",
        "Intel Core i7",
        "Intel Core i9",
        "Ryzen 3",
        "Ryzen 5",
        "Ryzen 7",
        "Ryzen 9",
        "Apple M1",
        "Apple M2",
      ],
    },
    {
      code: "generation",
      name: "Generation",
      type: "select",
      is_filterable: true,
      options: [
        "10th Gen",
        "11th Gen",
        "12th Gen",
        "13th Gen",
        "14th Gen",
        "15th Gen",
      ],
    },
    { code: "graphics", name: "Graphics", type: "text", is_filterable: true },
    { code: "battery_life", name: "Battery Life", type: "text" },
    {
      code: "warranty",
      name: "Warranty",
      type: "select",
      is_filterable: true,
      options: ["6 months", "1 Year", "2 Years", "3 Years", "Lifetime"],
    },
    {
      code: "connectivity",
      name: "Connectivity",
      type: "select",
      is_filterable: true,
      options: ["Wi-Fi", "Bluetooth", "NFC", "5G", "4G", "Thunderbolt"],
    },
    {
      code: "os",
      name: "Operating System",
      type: "select",
      is_filterable: true,
      options: ["Windows", "macOS", "Android", "iOS", "Chrome OS", "Linux"],
    },
  ],

  mobile_phones: [
    {
      code: "ram",
      name: "RAM",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: ["4GB", "6GB", "8GB", "12GB", "16GB", "18GB"],
    },
    {
      code: "storage",
      name: "Storage",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: ["64GB", "128GB", "256GB", "512GB", "1TB"],
    },
    {
      code: "color",
      name: "Color",
      type: "select",
      is_variant: true,
      is_filterable: true,
      options: [
        "Black",
        "White",
        "Blue",
        "Green",
        "Purple",
        "Silver",
        "Gold",
        "Graphite",
        "Red",
        "Titanium",
      ],
    },
    {
      code: "screen_size",
      name: "Screen Size",
      type: "select",
      is_filterable: true,
      options: ['5.4"', '6.1"', '6.7"', '6.8"', '6.9"'],
    },
    { code: "battery", name: "Battery", type: "number", suffix: "mAh" },
    { code: "camera_rear", name: "Rear Camera", type: "text" },
    { code: "camera_front", name: "Front Camera", type: "text" },
    {
      code: "refresh_rate",
      name: "Refresh Rate",
      type: "select",
      is_filterable: true,
      options: ["60Hz", "90Hz", "120Hz", "144Hz", "165Hz"],
    },
    {
      code: "os",
      name: "OS",
      type: "select",
      is_filterable: true,
      options: ["Android", "iOS"],
    },
    {
      code: "processor",
      name: "Processor",
      type: "select",
      is_filterable: true,
      options: [
        "Snapdragon",
        "Exynos",
        "Dimensity",
        "A-series",
        "Google Tensor",
      ],
    },
  ],

  grocery: [
    {
      code: "weight",
      name: "Weight",
      type: "number",
      suffix: "kg",
      is_filterable: true,
    },
    { code: "net_weight", name: "Net Weight", type: "number", suffix: "g" },
    { code: "expiry_date", name: "Expiry Date", type: "date" },
    { code: "organic", name: "Organic", type: "boolean", is_filterable: true },
    {
      code: "vegetarian",
      name: "Vegetarian",
      type: "boolean",
      is_filterable: true,
    },
    { code: "vegan", name: "Vegan", type: "boolean", is_filterable: true },
    {
      code: "gluten_free",
      name: "Gluten Free",
      type: "boolean",
      is_filterable: true,
    },
    { code: "brand", name: "Brand", type: "text", is_filterable: true },
    {
      code: "package_type",
      name: "Package",
      type: "select",
      is_filterable: true,
      options: ["Pouch", "Bottle", "Tin", "Jar", "Box", "Packet", "Can", "Bag"],
    },
    { code: "shelf_life", name: "Shelf Life", type: "text" },
  ],

  beauty_personal_care: [
    {
      code: "shade",
      name: "Shade",
      type: "select",
      is_variant: true,
      is_filterable: true,
    },
    {
      code: "skin_type",
      name: "Skin Type",
      type: "select",
      is_filterable: true,
      options: ["Normal", "Oily", "Dry", "Combination", "Sensitive"],
    },
    {
      code: "concern",
      name: "Skin Concern",
      type: "select",
      is_filterable: true,
      options: [
        "Acne",
        "Anti-Aging",
        "Hydration",
        "Brightening",
        "Dark Spots",
        "Pores",
        "Oil Control",
      ],
    },
    {
      code: "size",
      name: "Size",
      type: "select",
      is_filterable: true,
      options: ["15ml", "30ml", "50ml", "100ml", "200ml", "Travel Size"],
    },
    {
      code: "fragrance",
      name: "Fragrance",
      type: "select",
      is_filterable: true,
    },
    {
      code: "cruelty_free",
      name: "Cruelty Free",
      type: "boolean",
      is_filterable: true,
    },
    {
      code: "spf",
      name: "SPF",
      type: "select",
      is_filterable: true,
      options: ["15", "30", "50", "50+", "None"],
    },
    {
      code: "paraben_free",
      name: "Paraben Free",
      type: "boolean",
      is_filterable: true,
    },
    {
      code: "sulfate_free",
      name: "Sulfate Free",
      type: "boolean",
      is_filterable: true,
    },
  ],

  home_kitchen: [
    { code: "color", name: "Color", type: "select", is_filterable: true },
    { code: "material", name: "Material", type: "select", is_filterable: true },
    { code: "size", name: "Size", type: "select", is_filterable: true },
    { code: "capacity", name: "Capacity", type: "number", suffix: "L" },
    { code: "wattage", name: "Wattage", type: "number", suffix: "W" },
    {
      code: "voltage",
      name: "Voltage",
      type: "select",
      is_filterable: true,
      options: ["220-240V", "110-120V", "Dual Voltage"],
    },
    {
      code: "type",
      name: "Product Type",
      type: "select",
      is_filterable: true,
      options: ["Cookware", "Appliance", "Utensil", "Cutlery", "Storage"],
    },
  ],

  toys_games: [
    {
      code: "age_group",
      name: "Age Group",
      type: "select",
      is_filterable: true,
      options: [
        "0-2 Years",
        "2-4 Years",
        "4-6 Years",
        "6-8 Years",
        "8-12 Years",
        "12+ Years",
      ],
    },
    { code: "material", name: "Material", type: "select", is_filterable: true },
    { code: "theme", name: "Theme", type: "select", is_filterable: true },
    {
      code: "gender",
      name: "Target Gender",
      type: "select",
      is_filterable: true,
      options: ["Boys", "Girls", "Unisex"],
    },
    { code: "battery_required", name: "Battery Required", type: "boolean" },
  ],

  books: [
    { code: "author", name: "Author", type: "text", is_filterable: true },
    { code: "publisher", name: "Publisher", type: "text", is_filterable: true },
    {
      code: "language",
      name: "Language",
      type: "select",
      is_filterable: true,
      options: ["English", "Hindi", "Spanish", "French", "Regional"],
    },
    { code: "pages", name: "Pages", type: "number" },
    {
      code: "binding",
      name: "Binding",
      type: "select",
      is_filterable: true,
      options: ["Paperback", "Hardcover", "Kindle", "Spiral", "Audio"],
    },
    {
      code: "genre",
      name: "Genre",
      type: "select",
      is_filterable: true,
      options: [
        "Fiction",
        "Non-Fiction",
        "Romance",
        "Thriller",
        "Self-Help",
        "Children's",
      ],
    },
    { code: "isbn", name: "ISBN", type: "text" },
  ],
};
