const path = require("path");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    path.join(__dirname, "src/**/*.{js,ts,jsx,tsx,mdx}"),
    path.join(__dirname, "../../packages/**/*.{js,ts,jsx,tsx,mdx}"),
  ],

  // TEMP DEBUG: force-generate rules used in blocks
  safelist: [
    ...[
      "mx-auto",
      "max-w-6xl",
      "max-w-2xl",
      "px-4",
      "py-10",
      "py-8",
      "p-3",
      "text-3xl",
      "text-xl",
      "text-sm",
      "font-semibold",
      "leading-tight",
      "mt-3",
      "mt-6",
      "opacity-80",
      "opacity-90",
      "inline-flex",
      "rounded",
      "bg-black",
      "text-white",
      "grid",
      "grid-cols-2",
      "gap-4",
      "border",
      "transition",
      "hover:shadow-sm",
      "md:text-5xl",
      "md:text-lg",
      "md:grid-cols-4",
      "flex",
      "items-center",
      "space-x-3",
      "space-y-1",
      "hover:underline",
      "justify-center",
      "w-10",
      "h-10",
      "rounded-full",
      "bg-gray-200",
      "text-gray-600",
      "hover:bg-gray-300",
      "items-center",
      "justify-between",
      "w-full",
      "max-w-xl",
      "text-center",
      "text-4xl",
      "font-bold",
      "p-4",
      "mx-auto",
      "max-w-6xl",
      "px-4",
      "py-10",
      "text-3xl",
      "md:text-5xl",
      "font-semibold",
      "leading-tight",
      "mt-3",
      "text-base",
      "md:text-lg",
      "opacity-85",
      "max-w-2xl",
      "mt-6",
      "inline-flex",
      "px-4",
      "py-2",
      "rounded",
      "bg-black",
      "text-white",
      "flex",
      "items-center",
      "justify-between",
      "gap-4",
      "py-3",
      "overflow-x-auto",
      "text-sm",
      "whitespace-nowrap",
      "hover:opacity-100",
      "px-3",
      "py-8",
      "flex-col",
      "gap-3",
      "opacity-75",
      "flex-wrap",
      "gap-x-4",
      "gap-y-2",
      "text-xl",
      "mt-4",
      "grid",
      "grid-cols-2",
      "md:grid-cols-4",
      "gap-4",
      "border",
      "p-3",
      "hover:shadow-sm",
      "transition",
      "font-medium",
      "mt-1",
      "col-span-2",
      "md:col-span-4",
      "opacity-70",
    ],
    {
      pattern:
        /(p|m|px|py|pt|pb|pl|pr|gap|space-x|space-y|inset|top|right|bottom|left)-/,
    },
    {
      pattern:
        /(bg|text|border|ring|fill|stroke)-(red|green|blue|yellow|gray|slate|zinc|neutral|stone|amber|orange|pink|purple|indigo|cyan|teal|emerald|lime|fuchsia|violet|rose|white|black)/,
    },
    {
      pattern:
        /(flex|grid|col-span|row-span|order|justify|items|content|self|place-)/,
    },

    // Borders & rounded & shadow
    { pattern: /(border|rounded|shadow)/ },
    {
      pattern:
        /(transition|duration|ease|delay|transform|scale|rotate|translate)/,
    },

    // Common states – add only what you need (this grows fast!)
    {
      pattern: /(hover:|focus:|active:|disabled:|dark:|lg:|md:|sm:|xl:)/,
      variants: [
        "hover",
        "focus",
        "active",
        "disabled",
        "dark",
        "lg",
        "md",
        "sm",
        "xl",
      ],
    },
  ],

  theme: { extend: {} },
  plugins: [],
};
